[package]
name = "cases"
version = "0.0.6"
edition = "2021"

[dependencies]
askama = { version = "0.12", default-features = false }
axum = { version = "0.7", features = ["http2", "query", "tokio", "http1"], default-features = false }
basic-toml = "*"
bincode = "1.3.3"
csv = "1"
indexmap = "2"
redb = "2.1.4"
serde = { version = "1", features = ["derive"] }
stop-words = "0.8.0"
tantivy = "0.22.0"
tantivy-jieba = "0.11.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tower = "0.5"
tower-http = { version = "0.6", features = ["compression-br", "trace", "timeout"] }
tracing = { version = "0.1", features = ["release_max_level_info", "max_level_info"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
zip = { version = "2.1.6", default-features = false, features = ["deflate"] }
zstd = { version = "0.13.2", default-features = false }

[dev-dependencies]
jieba-rs = "0.7.0"

[profile.release]
lto = "fat"
strip = true
codegen-units = 1
panic = "abort"
rpath = false
